### ISSUE TITLE
When having CacheControl directive this executor context has side effect

### ISSUE THREAD

**Issue by maapteh** [zalando-incubator/graphql-jit#105]
It actually calls the internal cache plugin of apollo twice when having [this executor](https://github.com/zalando-incubator/graphql-jit/blob/master/examples/blog-apollo-server/src/executor.ts) operational. Maybe its wise for the plugin to have compatibility check with frameworks? So people can see what works and doesn't :) 

The cache setup is triggered by 'requestDidStart'

https://github.com/zalando-incubator/graphql-jit/blob/ef85d2d628e2aeda304067b28600bf2c0b9c8086/examples/blog-apollo-server/src/server.ts#L13

so when i add just like this and enable cacheControl in Apollo it creates the side effect that apollo does mGet (a Redis get) twice when having a custom executor. So the combi cacheControl and jit is not a good one, maybe thats why it never gets an official Apollo plugin ? Shame because it DID optimize the amount of executions :(

https://github.com/apollographql/apollo-server/issues/4876

**Comment by ruiaraujo** [comment]
I am not following what the issue is.

**Comment by maapteh** [comment]
Ok, we have a cacheControl van Apollo and saw for single query it called twice Redis instead of once.
Then we found out when removing the custom executor it returned back to calling Redis only once.

Since the Apollo caching is only operating on requestDidStart it was weird to actually see it being called twice. I have no idea why this happens, but if you need i can make reproduction in which you set breakpoint in package 'apollo-server-caching' when calling of item in cache.

**Comment by maapteh** [comment]
Ok i found it, its the damn cache plugin when having private key on public cachecontrolled query it still first tries to get wit private session one :(

Sorry!
