### ISSUE TITLE
Caching compiled queries

### ISSUE THREAD

**Issue by FilipLeonard** [zalando-incubator/graphql-jit#116]
In the context of a serverless architecture, would it be possible to cache the compiled queries (e.g. using ElastiCache w. Redis). Is it even worth caching the queries? If so, do you have any specific recommendations?

**Comment by ruiaraujo** [comment]
We stored Persisted queries in a stateful storage, depending on the amount of metadata and what you intend to do with the data, you might diffferent options.

The result of the compilation can't be serialized at the moment hence it can not be cached. We follow a lazy model when the first request caches the compiled query.
