### ISSUE TITLE
[RangeError: invalid String length]

### ISSUE THREAD

**Issue by fjmoreno** [zalando-incubator/graphql-jit#117]
Hello,

Im getting an error when use skip/inlude in a deep node, this error comes from this function:
https://github.com/zalando-incubator/graphql-jit/blob/15ec15fb61e0f0998725147ebb1f75c00e829d22/src/ast.ts#L301-L331

More specifically from at .join on line 330, the reason of that is that this function deduplicate multiples trues but it fails to deduplicate of the conditions comes from a variables, repeating multiple times same condition on the __internalShouldInclude, 

for example, if you have a nested skip/include with a var:
```javascript
....
@skip(if: $includeOnly)
....
```

you can get this __internalShouldInclude:
```javascript
(__context.variables["includeOnly"] === false) && (__context.variables["includeOnly"] === false) &&  (__context.variables["includeOnly"] === false) && (__context.variables["includeOnly"] === false) && (__context.variables["includeOnly"] === false) && (__context.variables["includeOnly"] === false) &&  (__context.variables["includeOnly"] === false) && (__context.variables["includeOnly"] === false)
.......................................
```

Must deduplicate it to ensure not exceed v8 max string length

**Comment by fjmoreno** [comment]
i workarounded it replacing the code of the above referenced function with this one:
```javascript
function joinShouldIncludeCompilations(...compilations: string[]) {
  // remove empty strings
  let filteredCompilations = compilations.filter(it => it);

  /**
   * If we have already computed conditions in form of A && B && C, we
   * must split it into individual conditions and flatten it
   */
  filteredCompilations = ([] as string[]).concat(
    ...filteredCompilations.map(e => e.split(" && "))
  );
  /**
   * We must to deduplicate it to make sure that every condition is only one time on resulting array
   */
  filteredCompilations = Array.from(new Set(filteredCompilations));
  return filteredCompilations.join(" && ");
}

```

**Comment by ruiaraujo** [comment]
/@fjmoreno Care to propose a PR with a test?

**Comment by fjmoreno** [comment]
I tried to write the test but im unsure how to test it, i'll explain, joinShouldIncludeCompilations is not exported so i can't test it directly and it's doesn't see a easy way of test it through the full process of compile a query, i also looked for a test of the current behavior and did not found it, any idea? thanks.

**Comment by ruiaraujo** [comment]
I would strongly prefer a query that showcases the issue. It makes for a much stronger test.
We dont export most methods to drive this style of testing.

All tests compile a query.

**Comment by fjmoreno** [comment]
i not suggesting to export that function, if its private its private, and I'm not trying to get into a debate if test isolated public functions  is a better approach or not, in this case the only way is what you suggest but the only thing i can think of is to write a test with a .not.toThrow failing in the current implementation and passing in the new one but to reproduce it i need a complex schema that allows to write a very nested field, so as the new implementation is a generalization of the current impl, what im asking is if you already have a test for the current implementation so i can use that query, sorry but the real case is a huge query(1000+ lines including many fragments) and i have not much time right now to think about how to simplify it to mock same case so ill appreciate if you have an easier idea (or a test for the current implementation as i said).

Thank you.

**Comment by ruiaraujo** [comment]
The issue seems to be caused by nested fragments with the directive right?

I dont think the schema complexity is a driver, we could create a recursive schema and generate a query large enough to trigger the bug. Would that work?

**Comment by fjmoreno** [comment]
sorry for the silence, as I said, I'm a little busy, I'll try later today
