### ISSUE TITLE
Input type defaults not supported?

### ISSUE THREAD

**Issue by laurisvan** [zalando-incubator/graphql-jit#142]
Our stack is using a combination of apollo-server-express (to be removed), graphql-envelop, graphql-modules, and now recently we were adding graphql-jit.

While the stack works alright otherwise, it appears that out input type defaults do not get applied in mutations. A sample:

```
input CustomerInput {
  id: ID
  type: CustomerType = WORK_SITE
}
```

Before digging further, I'd like to get your confirmation whether input type defaults should be working, or is this something new? Could this be related to using ENUMs or something else? Is there a working sample/test/whatever that I could try and extend?

**Comment by laurisvan** [comment]
Effectively this works when the type is set not nullable. I wonder if this is somehow related to https://github.com/zalando-incubator/graphql-jit/issues/91 ?

**Comment by ruiaraujo** [comment]
I need to check the spec to understand the right behaviour. If you contribute a failing test, it will help. :)

**Comment by laurisvan** [comment]
@ruiaraujo Will be glad to write one. Can you give a bit of hint on the structure of tests in this repo - where should such a test go? 

Could https://github.com/zalando-incubator/graphql-jit/blob/master/src/__tests__/variables.test.ts 
```
const TestInputObject = new GraphQLInputObjectType({
  name: "TestInputObject",
  fields: {
    a: { type: GraphQLString },
    b: { type: new GraphQLList(GraphQLString) },
    c: { type: new GraphQLNonNull(GraphQLString) },
    d: { type: TestComplexScalar },
    e: { type: new GraphQLList(GraphQLString) }
  }
});
```

be extended with an input type with a default?

**Comment by laurisvan** [comment]
I think the corresponding spec is https://spec.graphql.org/June2018/#sec-Input-Objects, "Input Coercion":

```
If a variable is provided for an input object field, the runtime value of that variable must be used. If the runtime value is null and the field type is non‐null, a field error must be thrown. If no runtime value is provided, the variable definition’s default value should be used. If the variable definition does not provide a default value, the input object field definition’s default value should be used.
```

I'm not fully sure how graphql-jit implementation of null values works - My reading of the spec tells that if the input field is specifically given as null, it should be treated as null; but if missing, should be coerced to default.

**Comment by KariHe** [comment]
I have created unit test to demonstrate the issue. Tests can be found from https://github.com/KariHe/graphql-jit/tree/input-defaults-tests (Should I open PR to get them in?)

When input is given directly in request defaults are working.
`query {
  fieldWithDefaultInputValue(input: { a: "test" })
}`

But when it is variable then defaults are not applied.
`query ($value: TestInputObjectWithDefaultValue!) {
  fieldWithDefaultInputValue(input: $value)
}`

**Comment by ruiaraujo** [comment]
Yes, please open a PR. Once the build fails with the error we can skip the test and merge it in

**Comment by laurisvan** [comment]
@ruiaraujo Since the problem seems to be related for input variables and works in literals, could you guide us a bit on what would be the relevant bits to check & fix? We're still a bit unfamiliar with the codebase.

**Comment by ruiaraujo** [comment]
Variables are handled quite differently. This whole coertion part needs some refactoering which might a bit too intense for a first contribuition.

**Comment by laurisvan** [comment]
Ok. Since this thing has existed for quite a while without discovering it, I expect there's no immediate business need for this in Zalando, so we probably should not set our hopes too high.  Is there any way we could contribute to make this happen?

**Comment by ruiaraujo** [comment]
@laurisvan you're selling us short. :smile: 
I am almost done with the fix.

**Comment by laurisvan** [comment]
@ruiaraujo Sir, I owe you a beer. :)

I'll test this first thing in the morning with fresh eyes!

**Comment by laurisvan** [comment]
We faced another problem when trying this out - might be completely subscription related and probably wholly different from this issue. It appears that when mixing literals with variables in subscription parameters, it appears that the literals in parameters do not appear in subscription args. Since we've got quite many layers (through graphql envelop) in-between, I'm not confident it is due to graphql-jit, but appears when adding it.

Here's a sample of our payload (fragment omitted for brevity): 
```
 subscription OnTeamUpdate($assignmentIds: [ID!]!, $profileIds: [ID!], $limit: Int) {
  activityLogEntriesNew(
    semantics: [PLAN_ASSIGNMENT, REMOVE_PLAN_ASSIGNMENT, UPDATE_ASSIGNMENT, CREATE_ASSIGNMENT, ASSIGN_ASSIGNMENT, UNASSIGN_ASSIGNMENT, SET_ASSIGNMENT_BLOCKED, CREATE_OFFER, ACCEPT_OFFER, REJECT_OFFER, INVALIDATE_OFFER, CREATE_INQUIRY, ACCEPT_INQUIRY, REJECT_INQUIRY, INVALIDATE_INQUIRY, CANCEL_ASSIGNMENT, CONFIRM_ASSIGNMENT, UNCONFIRM_ASSIGNMENT, UNBLOCK_ASSIGNMENT, START_ASSIGNMENT, FINISH_ASSIGNMENT, SET_PRESENT_ASSIGNMENT, SET_AWAY_ASSIGNMENT, ACCEPT_ASSIGNMENT, REOPEN_ASSIGNMENT, TOUCH_ASSIGNMENT, CREATE_COMPENSATION, UPDATE_COMPENSATION, DELETE_COMPENSATION, CREATE_ASSIGNMENT_REPORT, UPDATE_ASSIGNMENT_REPORT, DELETE_ASSIGNMENT_REPORT, DELETE_ASSIGNMENT, DELETE_PROFILE]
    queryType: OR
    assignmentIds: $assignmentIds
    profileIds: $profileIds
    limit: $limit
  ) {
    ...OnTeamUpdate
  }
}
```

I'll try to compose this into a separate issue and a test case - I believe it isn't related to this one.
