### ISSUE TITLE
Link to site in About section here doesn't work

### ISSUE THREAD

**Issue by smolinari** [zalando-incubator/graphql-jit#154]
Hi,

The link https://try-graphql-jit.boopathi.in/ in the About section in this repo, or rather the app behind it doesn't seem to be working. Gives a sort of bad impression. 

![image](https://user-images.githubusercontent.com/3314957/145155650-7fd2e811-095d-49e0-b094-046445ba8f53.png)

Scott

**Comment by boopathi** [comment]
Thanks for the report. I did not realize that the runtime was broken likely because of parcel rc upgrade. I've fixed it now and the link works.

**Comment by smolinari** [comment]
@boopathi - Is the first execution supposed to fail? 

![image](https://user-images.githubusercontent.com/3314957/145334309-cea062de-ef18-4898-9e26-232638a90576.png)

Scott

**Comment by boopathi** [comment]
No. It's not supposed to fail. But I do see repeatedly that it fails often the first time we click execute button. Looks like the worker download or cold start might be causing the slowness. I've removed the timeout for first time execution. This is the repo for try-graphql-jit - https://github.com/boopathi/try-graphql-jit .
