### ISSUE TITLE
GraphQL 17 support?

### ISSUE THREAD

**Issue by igrlk** [zalando-incubator/graphql-jit#184]
Hey everyone ✋. I'm currently working on adding `@defer` directive support to Mercurius GraphQL server [here](https://github.com/mercurius-js/mercurius/pull/898).
And it looks like some of the tests in Mercurius where it interacts with graphql-jit, and most of the tests in this repo are failing against the new major version of GraphQL (version 17, which is in alpha yet).

Are there any plans on adding support for `graphql@17`? Also, how open are you to the PRs from the community to add support for `graphql@17`, in case someone will want to contribute?

Looking forward to hearing from you. Thanks! 👍

**Comment by boopathi** [comment]
https://github.com/zalando-incubator/graphql-jit/pull/185 is merged.
