### ISSUE TITLE
Filters not resolving properly?

### ISSUE THREAD

**Issue by firasdib** [zalando-incubator/graphql-jit#25]
Hi,

I'm having a bit of an issue with filters right now, which is confusing me.

I have a query which looks something like this:

```
query Foo($bar: String!) {
  system() {
    component(filter: { someKey: [$bar] }) {
     ...
  }
}
```

When I check the filter in the args passed to the resolvers, it's an empty object. If I change the filter to

```
    component(filter: { someKey: $bar }) {
```

I see the correct value in the filter.

Am I doing something wrong, or is there potentially a bug here?

Thanks.

**Comment by firasdib** [comment]
Here's a bare minimum example using the standard graphql compiler for js, and it seems to work there.

```js
var { graphql, buildSchema } = require('graphql');

var schema = buildSchema(`
  type Query {
    world(filter: SomeFilter): String
  }

  input SomeFilter {
    foo: [String]
  }
`);

var root = {
  world: (args) => {
    console.log(args);
    return 'Hello';
  },
};

const query = `
query Somgpiajpae($someString: String!) {
  world(filter: { foo: [$someString] })
}
`;
const variables = {
  someString: 'world',
};

graphql(schema, query, root, undefined, variables);
```

**Comment by ruiaraujo** [comment]
This is a known issue that I am tackling right now. It is a bigger change that one might expect. the workaround is using top level variables

`query Somgpiajpae($someStringList: [String]!) {
  world(filter: { foo: $someStringList })
}`

I expect to have this fixed within the next week.

**Comment by firasdib** [comment]
Thanks for the swift reply. 

I’m going to stick with the reference implementation for now, as we rely heavily on this feature. When you’ve got a fix ready, I’d be happy to try it out and benchmark it.

**Comment by antonkuzmin** [comment]
@ruiaraujo I'm stuck with this problem too.
Could you publish this fix to NPM so I can check it?

**Comment by ruiaraujo** [comment]
@antonkuzmin @firasdib I am curious about your results so reach out if you can share them.
