### ISSUE TITLE
Node configuration recommendations

### ISSUE THREAD

**Issue by wojtkiewicz** [zalando-incubator/graphql-jit#52]
Hi,
I'm running `graphql-jit` in production (as custom executor for Apollo GraphQL) and its performing worse than regular `graphql-js` implementation (higher cpu usage with similar throughput). I can see a difference in favor of `graphql-jit` when running benchmark (similar to `schema-many-resolvers.benchmark.ts`) but can't reproduce this in production setting. Results of `compileQuery` are cached properly between consecutive calls.

Do you have any recommendations for custom node config?
Do you have to tweak inlining options for v8 (like `max-inlined-bytecode-size`) for `graphql-jit` to work properly?

**Comment by ruiaraujo** [comment]
which version of Nodejs/v8 are you using?

What kind of objects do your many resolvers return? Do they vary a lot in shapes, prototypes?
We are not tweaking v8.

**Comment by wojtkiewicz** [comment]
I'm using v10.15 (LTS).

Queries are stable with respect to structure (parameterized, they hit compiled-query-cache all the time) but schema has a lot of optional fields that are nested in multidimensional arrays (common search result scenario where each record on a list has a lot of properties that can be quite complex). Typical response weights around 100-200kb.

I also noticed that `graphql-jit` is performing especially worse when app is querying for `__typename` extensively.

**Comment by ruiaraujo** [comment]
Do you return a specific field for the typename or rely on the instance type to figure it out?

**Comment by ruiaraujo** [comment]
@wojtkiewicz your use case seems quite interesting, if you could share a flamechart based on https://clinicjs.org/flame/ or something similar it would be easier to track down where it is deopting.

**Comment by wojtkiewicz** [comment]
I don't have any specific resolvers for `__typename`. I have a bunch of flamegraphs from clinic already but I need to check what kind of stuff I can leak to the internet.

**Comment by ruiaraujo** [comment]
@wojtkiewicz I found a regression that we introduced with #31. I also have another idea (inlining __typename) but it should be residual after #53.

**Comment by wojtkiewicz** [comment]
@ruiaraujo that's a great news. I'm still working on a flamegraph because I'm afraid I need to make it look like we're running a cookie store. I should have something for tomorrow.

Apparently `__typename` field is queried by `apollo-ios` when you introduce conditional fragments to your queries. I'm expecting Android graphql implementations to do the same.

> Apollo iOS automatically augments your queries to add a __typename field to selection sets. This is used primarily to support conditional fragments, but it means a __typename property is always defined and can be used to differentiate between object types manually if needed.
[source: apollo-ios](https://github.com/apollographql/apollo-ios/blob/855e8fd6826f3786cd804b7b7e1fd8260a82208d/docs/source/fragments.md)

**Comment by ruiaraujo** [comment]
How large are the arrays btw in average?

**Comment by wojtkiewicz** [comment]
Total number of elements in all arrays should be in hundreds rather than thousands.

Arrays itself are usually up to 100 elements but they are nested a little like this:
`{a: { a1: [{ /* more arrays */}], a2: [{ /* more arrays */ }]}, b: [...], c: [...]}`.

So depending on particular search result we can have different dimensions present (a little like searching for all *blue* clothing items on zalando).

**Comment by ruiaraujo** [comment]
Can you try with new version `0.3.3` and see if there are improvements?

**Comment by wojtkiewicz** [comment]
@ruiaraujo I tested `0.3.3` today on canary and I can definitely see an improvement over `0.3.2` but I'm afraid performance is on par with `graphql-js`.

I'm starting to think that maybe integration with `apollographql` prevents v8 optimizations to trigger [(source)](https://github.com/apollographql/apollo-server/blob/aec3e02d31e081d7bda397a9674f965d190eee28/packages/apollo-server-core/src/requestPipeline.ts#L459).

I'm going to redo flamegraph for latest version (no point showing you old one). Are you comfortable with just `*.cpuprofile`? I'm having a little trouble converting it to proper flamegraph in svg format because all tools I tried failed (e.g. 0x).

**Comment by ruiaraujo** [comment]
At zalando, our graphql layer is a gateway where our models don't do much besides very basic mapping. It shines in this environment. 

I am fine with cpuprofile.

**Comment by wojtkiewicz** [comment]
I can contribute a benchmark. Just need a little time to make it less verbose.  

You should receive an invite to a private repo with anonymized cpuprofile. Let me know if content is still readable to you (there were several transformations to make it sharable). I also have a variant with `graphql-js` just to compare.

**Comment by ruiaraujo** [comment]
I took a look and doesn't look good. Contributing a benchmark is the easiest to have a go at that use case.


Using the apollo extensions resolver wrapper doesn't help you so I would suggest getting that off although there is always room for improvement on the jit implementation.

One thing that is not optimal, is the profiled code returning graphql errors? Specially on non-nullable fields?

**Comment by wojtkiewicz** [comment]
Thank you for the time you to took to study my cpuprofile. 

I'm investigating apollo extension stack as we speak. The only extension that should trigger is our custom metrics extension (and only around entire request processing, not after each individual field resolution). Rest of extensions that we use is behind feature flags and do not trigger everytime.

...but now that you mention extensions I found that apollo-cache-control can trigger by default after field resolution. I will try to disable this feature and see if it changes anything. Should affect both `graphql-js` and `graphql-jit` though.

There should not be any errors thrown in normal circumstances.

Anyway, thank you for your suggestions.

**Comment by wojtkiewicz** [comment]
@ruiaraujo I submitted a little benchmark with arrays in another thread. Nothing too fancy.

Btw I got rid off all extensions that trigger on field resolution (like `apollo-cache-control`) and I should have updated cpuprofile tomorrow (if you want to take a look).

**Comment by ruiaraujo** [comment]
In the meantime, I profiled the bytecode generated and saw a few closures that are not welcomed.

I will have to build v8 in debug mode to double check the assembly code.

**Comment by ruiaraujo** [comment]
@wojtkiewicz have you tried the latest version?

**Comment by wojtkiewicz** [comment]
@ruiaraujo sorry for such late response. I was stuck doing something else for a while. 

I will get back to this soon. We've been running vanilla `graphql-js` implementation in the meantime.

**Comment by wojtkiewicz** [comment]
@ruiaraujo I'm happy to say that I've managed to reproduce `graphql-jit` performance benefits in production :-)

v8 was deopting all this time in resolver's code itself, not in actual executor. I still need to work on our code a little bit to safely enable `disableLeafSerialization` though.

Sorry for such late response. We've been very busy before Christmas :-)

**Comment by ruiaraujo** [comment]
Thanks for the update @wojtkiewicz. I am closing this issue then.

**Comment by codecog** [comment]
@wojtkiewicz do you have any examples of how you went about integrating jit with apollo server? Seems like you've gained the benefits of using both together?

**Comment by ruiaraujo** [comment]
Looking at https://github.com/apollographql/apollo-server/blob/aec3e02d31e081d7bda397a9674f965d190eee28/packages/apollo-server-core/src/requestPipeline.ts#L459 it seems the config object can take a custom executor.

One improvement we could do is to have a guide for such an integration.
@codecog @wojtkiewicz it would be lovely. :wink:

**Comment by wojtkiewicz** [comment]
@codecog @ruiaraujo I can contribute a piece of code if you want. It's under 100 lines...

**Comment by codecog** [comment]
@wojtkiewicz would like to see it for sure.
