### ISSUE TITLE
Not working with custom directives

### ISSUE THREAD

**Issue by orefalo** [zalando-incubator/graphql-jit#6]

**Comment by ruiaraujo** [comment]
What would be the expectations here?

I have ideas of introducing a hook system to compile directives but it is very geared towards how I expect to use it.

**Comment by orefalo** [comment]
Well, I would expect the compiled function to call the directive implementation.

**Comment by ruiaraujo** [comment]
It depends on the directive implementation. `graphql-js` doesn't also include directive execution support.

What are you currently using to hook this?
Is it this?
https://www.apollographql.com/docs/graphql-tools/schema-directives.html#Uppercasing-strings

Furthermore, are your directive declared on the Schema level or on the Operation level?

**Comment by orefalo** [comment]
hum.. honestly I didn't write them. But I remember they worked equally well on apollo or graphql-js

https://github.com/APIs-guru/graphql-constraints-spec
https://github.com/APIs-guru/graphql-lodash
https://github.com/apollo-9/graphql-schema-value-validation
https://github.com/excitement-engineer/graphql-iso-date
https://github.com/teamplanes/graphql-rate-limit

**Comment by ruiaraujo** [comment]
I think we need to consider a field that has a directive to behave like it has an explicit directive and it should be enough.

**Comment by orefalo** [comment]
Sorry for the late reply - got distracted over the last few months.
Agreed! in fact, it shouldn't be that hard to implement and in the end @directives are very much like function calls (with parameters)

**Comment by bionicles** [comment]
interested in this library but directives are mission critical, and the Apollo Server implementation is super verbose OOP, would it be possible to register functions as directives with ability to designate if they run before or after query execution?

For example with a mutation you need the directive function to happen before you mutate the database. 

With a query you may want directives to run after query execution so you can filter out fields with ABAC authZ

**Comment by bionicles** [comment]
Also I’d argue implementing directives is not a good first issue because that’s expecting someone new to the codebase to implement a big feature. Whoever made this repo could you please add functional directives?

**Comment by boopathi** [comment]
If you're using `makeExecutableSchema` from `graphql-tools`, using a Schema Directives, you can add or overwrite a resolver to the field and it works with graphql-jit. You can find examples here - https://www.apollographql.com/docs/graphql-tools/schema-directives/ .. 

Also, I found that apollo avoids query directives and leave it to user land - https://www.apollographql.com/docs/graphql-tools/schema-directives/#what-about-query-directives 

To use query directives, one of the options is to use the details from the `Resolve info` param in the resolvers - 

```js
{
 Query: { 
    foo(parent, input, context, resolveInfo) { 
      resolveInfo.fieldNodes[0].directives
    }
  }
}
```

Is there something else that graphql-jit needs to do to support using directives?

**Comment by boopathi** [comment]
I'm closing this issue. Please comment with the case for which it doesn't work to re-open the issue.
