### ISSUE TITLE
Apollo server integration

### ISSUE THREAD

**Issue by guigaoliveira** [zalando-incubator/graphql-jit#67]
Hi, is it possible to integrate with apollo server?

**Comment by wojtkiewicz** [comment]
Yes, I did that successfully on production.

You can provide custom `executor` using `ApolloServerConfig` but to be honest this looks like a pretty repeatable code. 

@ruiaraujo I think I can contribute PR to this repo with such integration if you want.

**Comment by guigaoliveira** [comment]
Interesting, I would like to see some example, looks promising :)

**Comment by ruiaraujo** [comment]
@wojtkiewicz yes please.We only use Apollo tools at Zalando so a tried contribution would be very valuable.

**Comment by Taraluktus** [comment]
Would also love to see an example of it.

**Comment by wojtkiewicz** [comment]
@ruiaraujo Sorry to have kept you waiting. I had few side hustles to complete. I will contribute something this week.

**Comment by OliverCole** [comment]
Paging @benawad who may wish to add this to https://github.com/benawad/node-graphql-benchmarks when published.
