### ISSUE TITLE
Support skip and include

### ISSUE THREAD

**Issue by jgfidelis** [zalando-incubator/graphql-jit#68]
I know there is already a thread open about this but its almost a year old.
We really want to use this lib but the lack of this feature is why we cannot use it.

Any plans on implementing it? I am taking a look at the code to see if I would be able to send a PR but it looks a bit complicated for someone with no context to help, but I can spend more time on this probably.

Anyway, for the creators of this lib, implementing it would be much quicker and since `@skip` and `@include` are so widely used, is there anyway we can move forward with this feature?

Thanks and congrats on the great lib

**Comment by ruiaraujo** [comment]
I can't promise a date but I hope to tackle this some time soon.

Closing this in favor of the original ticket #17

**Comment by jgfidelis** [comment]
I implemented it in a bit of a primitive way (or very primitive :P). I will try to send a pr on the weekend just to know what you think about it, if what I did would be good enough or if its very far away from optimal.
