### ISSUE TITLE
Support createSourceEventStream?

### ISSUE THREAD

**Issue by mattkrick** [zalando-incubator/graphql-jit#74]
Wonderful package, lots to learn from, thank you for open sourcing it!

Any plans to support `createSourceEventStream` for subscriptions? Any tips on how I'd go about PRing it?

**Comment by ruiaraujo** [comment]
We dont have a use case but I took a look at the spec and the `graphql-js` implementation and it doesn't seem too difficult.

My advice is start with an iterative approach where we use `createSourceEventStream` from graphql-js and implement just the subscribe function. It is different enough that warrants its own top level entry for compilation like it is a separate execution function.

Later the `createSourceEventStream` can also be reimplemented. We took the same approach to variable parsing which were introduced much later.

We definitely welcome PRs and will help you go along. TDD is a good approach and copy pasting tests from `graphql-js` is acceptable. Our license already reflects the policy.

**Comment by hoangvvo** [comment]
For anyone wondering, I'm experimenting with subscription in my fork at https://github.com/hoangvvo/graphql-jit ([PR](https://github.com/hoangvvo/graphql-jit/pull/2/files))

It is currently passing all tests from https://github.com/graphql/graphql-js/blob/master/src/subscription/subscribe.js excepts one weird one at `resolves to an error for source event stream resolver errors` (I verified the the error object has the same shape but it fails to compare for some reason :/) (maybe @ruiaraujo can help me with this if possible)

There is one deep import at `graphql/subscription/mapAsyncIterator` but it should be easily reimplemented.

I'm using it in production right now (via [`@benzene/ws`](https://www.npmjs.com/package/@benzene/ws)) and do not see any problem yet.

Will make a PR to this repo it seems ok.

**Comment by ruiaraujo** [comment]
Opening a PR would be nice. :heart:

**Comment by RichardWright** [comment]
@hoangvvo How's the pr coming? Would love to give this a go via the main package.

**Comment by hoangvvo** [comment]
@RichardWright Hey, sorry I could not find the time for this lately, but hopefully I can find some this weekend to work on it!

**Comment by RichardWright** [comment]
@hoangvvo is there anything anyone can do to help?

**Comment by hoangvvo** [comment]
@RichardWright You can help reviewing this PR https://github.com/zalando-incubator/graphql-jit/pull/115. Thanks!
