### ISSUE TITLE
Unexpected token 'import'

### ISSUE THREAD

**Issue by ChristianBoehlke** [zalando-incubator/graphql-jit#76]
We would like to switch from [express-graphql](https://github.com/graphql/express-graphql) to [express-gql](https://github.com/benawad/express-gql) (which uses graphql-jit) and are having trouble with one of our queries: `import(id: Int!): Import`

The function `compileQuery(...)` returns the following error:
```
{"errors":[{"message":"Unexpected token 'import'"}]}
```

As far as I understand, graphql-jit compiles the query into a JS function and `import` is a reserved keyword in JavaScript but not in GraphQL.

Is there any way to modify the function generation so that those keywords are okay to use?

**Comment by ChristianBoehlke** [comment]
Thank you for the fast response and the fix!
Do you have a timeline on when https://github.com/zalando-incubator/graphql-jit/pull/78 will be released?

**Comment by ruiaraujo** [comment]
It should be now available.

**Comment by ChristianBoehlke** [comment]
Thanks. The fix worked like a charm.
