### ISSUE TITLE
GraphQL v15 support

### ISSUE THREAD

**Issue by frikille** [zalando-incubator/graphql-jit#79]
Hello,

GraphQL v15 was released recently and I'm curious if there is a plan to enable this lib with the new version?

**Comment by ruiaraujo** [comment]
We need to take a look if the breaking changes affect us.

**Comment by frikille** [comment]
Thanks!

I've run a quick test locally by forking the repo and upgrading the version. There were 2 failing tests, but only because of text changes in error messages.

I'm happy to help to investigate the breaking changes if you can give me some starting points about what exactly I need to look into.

**Comment by ruiaraujo** [comment]
I am surprised it was only two tests. Feel free to send a PR with the newer messages.
The peer version already accepts v15.
